# Site settings
title: 🤕 Clumsy AngeLJ  😇
url: "https://phoebe.tano.si"
baseurl: ""

# Build settings
production: false
incremental: true
source: src
destination: public
markdown: kramdown
exclude: [node_modules]

plugins:
  - jekyll-assets

assets:
  digest: false
  features:
    automatic_img_alt: false
    automatic_img_size: false
  sources:
    - _assets/scripts
    - _assets/sass
    - _assets/images
    - node_modules
