source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-assets'

gem 'pygments.rb'
gem 'nokogiri'
gem 'autoprefixer-rails'
gem 'uglifier'
gem 'babel-transpiler'
gem 'sprockets', '~> 4.0.beta', {
  require: false
}
gem "font-awesome-sass"
